sudo: required

services: docker

before_install:
  - docker-compose build
  - docker-compose up -d

script:
  - sleep 10
  - docker-compose exec -e SECRET_KEY=$SECRET_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e DATABASE_URL=$DATABASE_URL -e DEBUG_COLLECTSTATIC=$DEBUG_COLLECTSTATIC -e DISABLE_COLLECTSTATIC=$DISABLE_COLLECTSTATIC -e S3_BUCKET=$S3_BUCKET web python manage.py test