version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

    web:
        build: .
        volumes:
            - .:/development/minimalist
            - /etc/localtime:/etc/localtime:ro
        environment:
            TZ: Asia/Tokyo
        ports:
            - '8000:8000'
        depends_on:
            - db
        links:
            - db
        tty: true
        stdin_open: true