FROM python:3

ARG test

ENV TEST=$test
RUN echo TEST

ENV TEST=${test}
RUN echo TEST

RUN set

WORKDIR /development/minimalist

ADD requirements.txt /development/minimalist

RUN pip install -r requirements.txt

ADD . /development/minimalist

COPY . .
RUN python manage.py collectstatic --noinput
CMD ["web:", "gunicorn", "minimalist.wsgi"]