FROM python:3

ARG REPO="www.example.com"
RUN echo $REPO

ARG RAILS_ENV
RUN echo $RAILS_ENV

ARG AWS
RUN echo $AWS

ARG AWS2
RUN echo $AWS2

RUN set

WORKDIR /development/minimalist

ADD requirements.txt /development/minimalist

RUN pip install -r requirements.txt

ADD . /development/minimalist

COPY . .
RUN python manage.py collectstatic --noinput
CMD ["web:", "gunicorn", "minimalist.wsgi"]