# Generated by Django 3.1 on 2021-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thingstatus',
            old_name='status',
            new_name='name',
        ),
    ]
