# Generated by Django 3.1 on 2021-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0002_minimalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimalmodel',
            name='sell_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
