# Generated by Django 3.1 on 2021-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0003_auto_20210417_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='zebra0.jpg', upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
