# Generated by Django 3.1 on 2021-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0004_auto_20210417_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='obj_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
