# Generated by Django 3.1 on 2021-04-28 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimalmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='buy_date',
            field=models.DateField(verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='buy_price',
            field=models.IntegerField(verbose_name='購入金額'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='buy_reason',
            field=models.TextField(verbose_name='購入した理由'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='obj_image',
            field=models.ImageField(blank=True, default='default_thing_icon.png', null=True, upload_to='', verbose_name='物の画像'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='売却金額'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='sell_reason',
            field=models.TextField(blank=True, null=True, verbose_name='手放す理由'),
        ),
        migrations.AlterField(
            model_name='minimalmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='品物名'),
        ),
    ]
