# Generated by Django 3.1 on 2021-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0008_auto_20210428_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimalmodel',
            name='title',
            field=models.CharField(max_length=20, verbose_name='品物名'),
        ),
    ]
