# Generated by Django 3.1 on 2021-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0011_auto_20210512_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimalmodel',
            name='sell_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='売却金額'),
        ),
    ]
